@set SVC_NAME_KRCV=KUMHO_CITI_SFTP_RCV_SAP
@set SVC_NAME_JSVR=KUMHO_CITI_SFTP_JCO_SVR

@set JAVASERVICE=.\JavaService-2.0.10\JavaService.exe
@%JAVASERVICE% -uninstall %SVC_NAME_KRCV%
@%JAVASERVICE% -uninstall %SVC_NAME_JSVR%
